{% set name = "releasecmd" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ef26486e1f08f81bcd8235101ed69d631d0b42de9208b0d60c5d4bca118110d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=38.3.0
  run:
    - python >=3.5
    - setuptools >=38.3.0
    - twine

test:
  imports:
    - releasecmd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/releasecmd
  summary: releasecmd is a release subcommand for setup.py (setuptools.setup). the subcommand create a git tag and push, and upload packages to PyPI.
  dev_url: https://github.com/thombashi/releasecmd
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
